# Generated by Django 4.0.5 on 2022-06-15 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0014_alter_contents_order_alter_question_order'),
        ('lectures', '0013_alter_content_order_alter_module_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0002_modularquiz_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modularquiz',
            name='student',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FinalQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.course')),
                ('questions', models.ManyToManyField(blank=True, related_name='final_questions', to='practice.question')),
                ('student', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
