# Generated by Django 4.0.5 on 2022-06-09 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0002_remove_question_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={},
        ),
        migrations.RemoveField(
            model_name='contents',
            name='order',
        ),
    ]
