# Generated by Django 4.0.5 on 2022-06-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0003_alter_contents_options_remove_contents_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
    ]
