# Generated by Django 4.0.5 on 2022-06-10 15:56

from django.db import migrations
import lectures.fields


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0006_alter_question_options_remove_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=lectures.fields.OrderField(blank=True, default=0),
        ),
    ]
