# Generated by Django 4.0.5 on 2022-06-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0007_alter_question_options_question_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionfile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questionimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='questiontext',
            options={},
        ),
    ]
