# Generated by Django 4.0.5 on 2022-06-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0008_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'answer'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'choice'},
        ),
        migrations.AlterModelOptions(
            name='questionfile',
            options={'verbose_name': 'question_file'},
        ),
        migrations.AlterModelOptions(
            name='questionimage',
            options={'verbose_name': 'question_image'},
        ),
        migrations.AlterModelOptions(
            name='questiontext',
            options={'verbose_name': 'question_text'},
        ),
    ]
