# Generated by Django 4.0.5 on 2022-06-10 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('practice', '0009_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('questiontext', 'questionimage', 'questionfile', 'choice', 'answer')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
