# Generated by Django 4.0.5 on 2022-06-12 15:23

from django.db import migrations
import lectures.fields


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_alter_answer_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contents',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='contents',
            name='order',
            field=lectures.fields.OrderField(blank=True, default=0),
        ),
    ]
