# Generated by Django 4.0.5 on 2022-06-13 22:53

from django.db import migrations
import lectures.fields


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0013_alter_contents_question_alter_question_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='order',
            field=lectures.fields.OrderField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=lectures.fields.OrderField(blank=True),
        ),
    ]
