# Generated by Django 4.0.5 on 2022-06-06 01:01

from django.db import migrations
import lectures.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=lectures.fields.OrderField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=lectures.fields.OrderField(blank=True, default=0),
        ),
    ]
