# Generated by Django 4.0.5 on 2022-06-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0007_remove_bank_author_remove_bank_questions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lectures.course', unique=True),
        ),
    ]
