# Generated by Django 4.0.5 on 2022-06-13 22:53

from django.db import migrations
import lectures.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0012_alter_content_content_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=lectures.fields.OrderField(blank=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=lectures.fields.OrderField(blank=True),
        ),
    ]
