# Generated by Django 4.0.5 on 2022-06-15 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchingaction',
            name='done',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
